name: mlflow-project-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - mlflow
  - pip:
    - ipykernel